version: "3"

services:
  # MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    # volumes:
    #   - mongo_db:/data/db

  # Node app
  app:
    image: app
    build:
      context: .
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      NODE_ENV: DEVELOPMENT
      PORT: 5000
      SALT: 2
      JWT_SECRET: _NahiyanMuzahidMamunIbrahimSahin
      MONGO_URI_LOCAL: mongodb://mongo_db:27017
    depends_on:
      - mongo_db
    links:
      - mongo_db

# volumes:
#   mongo_db:
#     driver: local
